In [ ]:
'''data encoding>> converting categorical columns into numerical columns
'''

In [1]:
#nominal/one hot encoding > it breate binary vector for each categories
#example :single, married, seperated
#single : [1,0,0]
#married : [0,1,0]
#separated : [0,0,1]


In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder


In [4]:
df = pd.DataFrame({'status':['single','married','separated','single','single','separated','separated','married']})
encoder = OneHotEncoder()
encoder

OneHotEncoder()

In [10]:
encoded = encoder.fit_transform(df[['status']]).toarray()
encoded

array([[0., 0., 1.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [11]:
encoder.get_feature_names_out()

array(['status_married', 'status_separated', 'status_single'],
      dtype=object)

In [13]:
encoder_df = pd.DataFrame(encoded,columns=encoder.get_feature_names_out())
encoder_df

,status_married,status_separated,status_single
0,0.0,0.0,1.0
1,1.0,0.0,0.0
2,0.0,1.0,0.0
3,0.0,0.0,1.0
4,0.0,0.0,1.0
5,0.0,1.0,0.0
6,0.0,1.0,0.0
7,1.0,0.0,0.0


In [ ]:
#we can remove one columns, we when we know the two remaining columns the 3rd column automaticall get it's values
#so in one hot encoding always n-1 columns we can keep, one column always drop

In [14]:
df


,status
0,single
1,married
2,separated
3,single
4,single
5,separated
6,separated
7,married


In [15]:
encoder_df

,status_married,status_separated,status_single
0,0.0,0.0,1.0
1,1.0,0.0,0.0
2,0.0,1.0,0.0
3,0.0,0.0,1.0
4,0.0,0.0,1.0
5,0.0,1.0,0.0
6,0.0,1.0,0.0
7,1.0,0.0,0.0


In [16]:
df = pd.concat([df,encoder_df],axis=1)

In [17]:
df

,status,status_married,status_separated,status_single
0,single,0.0,0.0,1.0
1,married,1.0,0.0,0.0
2,separated,0.0,1.0,0.0
3,single,0.0,0.0,1.0
4,single,0.0,0.0,1.0
5,separated,0.0,1.0,0.0
6,separated,0.0,1.0,0.0
7,married,1.0,0.0,0.0


In [18]:
#we can also convert this using pandas


In [19]:
import seaborn as sns
df = sns.load_dataset('tips')
df.head()


,total_bill,tip,sex,smoker,day,time,size
0,16.99,1.01,Female,No,Sun,Dinner,2
1,10.34,1.66,Male,No,Sun,Dinner,3
2,21.01,3.50,Male,No,Sun,Dinner,3
3,23.68,3.31,Male,No,Sun,Dinner,2
4,24.59,3.61,Female,No,Sun,Dinner,4


In [26]:
#convert sex and smoker into onehot encoding.
from sklearn.preprocessing import OneHotEncoder
encoder = OneHotEncoder()
result= encoder.fit_transform(df[['sex','smoker']]).toarray()
encoder_df2 = pd.DataFrame(result, columns=['is_female','is_male','not_smoker','is_smoker'])
df = pd.concat([df,encoder_df2],axis=1)
df

,total_bill,tip,sex,smoker,day,time,size,is_female,is_male,not_smoker,is_smoker
0,16.99,1.01,Female,No,Sun,Dinner,2,1.0,0.0,1.0,0.0
1,10.34,1.66,Male,No,Sun,Dinner,3,0.0,1.0,1.0,0.0
2,21.01,3.50,Male,No,Sun,Dinner,3,0.0,1.0,1.0,0.0
3,23.68,3.31,Male,No,Sun,Dinner,2,0.0,1.0,1.0,0.0
4,24.59,3.61,Female,No,Sun,Dinner,4,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,0.0,1.0,1.0,0.0
240,27.18,2.00,Female,Yes,Sat,Dinner,2,1.0,0.0,0.0,1.0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,0.0,1.0,0.0,1.0
242,17.82,1.75,Male,No,Sat,Dinner,2,0.0,1.0,1.0,0.0


In [27]:
#label encoding >> assign unique labels for catgorical data
df

,total_bill,tip,sex,smoker,day,time,size,is_female,is_male,not_smoker,is_smoker
0,16.99,1.01,Female,No,Sun,Dinner,2,1.0,0.0,1.0,0.0
1,10.34,1.66,Male,No,Sun,Dinner,3,0.0,1.0,1.0,0.0
2,21.01,3.50,Male,No,Sun,Dinner,3,0.0,1.0,1.0,0.0
3,23.68,3.31,Male,No,Sun,Dinner,2,0.0,1.0,1.0,0.0
4,24.59,3.61,Female,No,Sun,Dinner,4,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,0.0,1.0,1.0,0.0
240,27.18,2.00,Female,Yes,Sat,Dinner,2,1.0,0.0,0.0,1.0
241,22.67,2.00,Male,Yes,Sat,Dinner,2,0.0,1.0,0.0,1.0
242,17.82,1.75,Male,No,Sat,Dinner,2,0.0,1.0,1.0,0.0


In [32]:
from sklearn.preprocessing import LabelEncoder
lencoder = LabelEncoder()


In [33]:
lencoder.fit_transform(df[['day']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:114: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


array([2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3,
       3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 3])

In [36]:
#check value
lencoder.transform([['Sun']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([2])

In [38]:
lencoder.transform([['Thur']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\preprocessing\_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


array([3])

In [39]:
#ordinal encoding >> here we pass specifical order in terms of hierarical
from sklearn.preprocessing import OrdinalEncoder
oecoder = OrdinalEncoder()

In [44]:
df =pd.DataFrame({'Qualification':['HS','COL','UG','PHD','HS','PG','COL','HS','COL','PG']})
df

,Qualification
0,HS
1,COL
2,UG
3,PHD
4,HS
5,PG
6,COL
7,HS
8,COL
9,PG


In [45]:
oecoder = OrdinalEncoder(categories=[['HS','COL','UG','PG','PHD']])

In [46]:
oecoder

OrdinalEncoder(categories=[['HS', 'COL', 'UG', 'PG', 'PHD']])

In [49]:
oecoder.fit_transform(df[['Qualification']])

array([[0.],
       [1.],
       [2.],
       [4.],
       [0.],
       [3.],
       [1.],
       [0.],
       [1.],
       [3.]])

In [52]:
#new data
oecoder.transform([['HS']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[0.]])

In [53]:
oecoder.transform([['PHD']])

c:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but OrdinalEncoder was fitted with feature names
  warnings.warn(


array([[4.]])

In [54]:
#target guided ordinal encoding
#based on relationship with target variable, and we have lot of unique categories
#when we are unable to apply one hot encoding
#replace the cate with the mean and median of respective group target

In [57]:
df=pd.DataFrame({'time':['lunch','bf','dinner','dinner','dinner','bf','lunch','dinner','dinner','bf','lunch','dinner','dinner','bf','lunch',],
              'total_bill':[120,130,120,80,90,100,125,85,90,100,120,110,100,90,85]})
df

,time,total_bill
0,lunch,120
1,bf,130
2,dinner,120
3,dinner,80
4,dinner,90
5,bf,100
6,lunch,125
7,dinner,85
8,dinner,90
9,bf,100


In [60]:
mean_price = df.groupby('time')['total_bill'].mean().to_dict()
mean_price

{'bf': 105.0, 'dinner': 96.42857142857143, 'lunch': 112.5}

In [61]:
df['time_encoded'] = df['time'].map(mean_price)
df

,time,total_bill,time_encoded
0,lunch,120,112.500000
1,bf,130,105.000000
2,dinner,120,96.428571
3,dinner,80,96.428571
4,dinner,90,96.428571
5,bf,100,105.000000
6,lunch,125,112.500000
7,dinner,85,96.428571
8,dinner,90,96.428571
9,bf,100,105.000000
