In [1]:
import numpy as np

In [2]:
np.zeros(5) #out : ndarray Array of zeros with the given shape, dtype, and order

array([0., 0., 0., 0., 0.])

In [4]:
np.ndim

<function ndim at 0x0000016E3DC34570>

In [5]:
np.zeros((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [8]:
#we have only zeros and ones not more then that


In [ ]:
arr = np.zeros((3,4)) #donates rows and columns

In [11]:
arr.ndim

2

In [22]:
#when we want something for 3d
arr2 = np.zeros((3,3,4)) #donates 3 rouws 4 columns 3 outer dimentions
#in simple language, 3 rows 4 columsn 3 set's (or 3 set's of 3 rows and 4 columns)

In [23]:
arr2

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [24]:
arr2.ndim

3

In [36]:
arr = np.zeros((2,2,3,4))
#2 set's of 2 sets of 3 rows 4 columsn

In [37]:
arr

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])

In [38]:
arr = np.ones((3,4))

In [39]:
arr

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [41]:
arr + 5 #add 5 to each

array([[6., 6., 6., 6.],
       [6., 6., 6., 6.],
       [6., 6., 6., 6.]])

In [42]:
arr *5 

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [43]:
arr /3

array([[0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333],
       [0.33333333, 0.33333333, 0.33333333, 0.33333333]])

In [46]:
arr+5 %4

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [47]:
arr-3

array([[-2., -2., -2., -2.],
       [-2., -2., -2., -2.],
       [-2., -2., -2., -2.]])

In [54]:
e= np.eye(3) #diagonal element will 1.
#return 2d array with once on the diagonal ans zero remaining all

In [53]:
e.ndim

2

In [58]:
np.empty((3,4))

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [59]:
np.empty((3,4))

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [64]:
np.empty(3)

array([1., 1., 1.])

In [66]:
np.empty((3,2), dtype=float) #return a new array of given shape and type, without initilizing entiries


array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [70]:
#optional
import random 
random.choice((1,2,3,4,5)) #before to generate random number between range

5

In [72]:
random.choice("nachiket")

'k'

In [74]:
random.randrange(1,10)

5

In [78]:
random.random() # a random no is generated between 0 (included ) and 1 (excluded)

0.9618994855201946

In [79]:
lis = [1,2,3,4,5]
lis

[1, 2, 3, 4, 5]

In [86]:
random.shuffle(lis) #it will shuffle the list


In [87]:
lis

[5, 2, 3, 4, 1]

In [88]:
lis[0]

5

In [90]:
random.uniform(7,14)

10.65956865577691

In [91]:
#using numpy
np.array([])

array([], dtype=float64)

In [92]:
#to have random numbers related concepts in numpy
np.random.random_sample()

0.6629844420874093

In [95]:
np.random.random_sample(4,).ndim #1d

1

In [96]:
np.random.random_sample((3,4))

array([[0.25515135, 0.24796276, 0.64610764, 0.92284791],
       [0.10099421, 0.85298765, 0.10802294, 0.14587233],
       [0.61897214, 0.79122854, 0.99886678, 0.87497905]])

In [99]:
np.random.random_integers(5)

C:\Users\nachi\AppData\Local\Temp\ipykernel_15996\339360557.py:1: DeprecationWarning: This function is deprecated. Please call randint(1, 5 + 1) instead
  np.random.random_integers(5)


4

In [100]:
np.random.rand(2)

array([0.34650219, 0.10486561])

In [102]:
np.random.rand(3,4)

array([[0.62180263, 0.56436166, 0.85036866, 0.84815782],
       [0.21803368, 0.92166669, 0.88956985, 0.78434594],
       [0.05290447, 0.10772335, 0.64057327, 0.67459979]])

In [103]:
np.random.randn(2,3)

array([[ 0.82216643,  0.11276556,  1.31439576],
       [ 1.59801937, -1.1426684 , -0.22113591]])

In [107]:
arr=np.random.randint(2,3, size=(3,4))

In [110]:
#to change the shape of array, but make sure it should be ixj , jxi format
#reshape paramenter should be multiplication of array size
arr.reshape(2,6)

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [111]:
arr.reshape(3,6)

ValueError: cannot reshape array of size 12 into shape (3,6)

In [114]:
arr.reshape(3,4)
#i*j = arr.size

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [115]:
#when you don't know row or column 
arr.reshape(2,-1)

array([[2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2]])

In [116]:
arr.reshape(-1,3)

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [119]:
arr.reshape(-33,3) #must know one value either row or column and negative values are avoided and set the correct one

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 2],
       [2, 2, 2]])

In [123]:
arr.reshape(12,1).base.shape #to check original array shpae

(3, 4)

In [124]:
arr.reshape(2,2,3)

array([[[2, 2, 2],
        [2, 2, 2]],

       [[2, 2, 2],
        [2, 2, 2]]])

In [126]:
arr.reshape(3,2,2) #here i*j*k = arr.size

array([[[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2]]])

In [129]:
#conditions on array
arr1 = np.random.randint(1,10, (5,6))
#telling that take values between 1-10, and it should 5 rows and 6 columns

In [130]:
arr1

array([[1, 2, 4, 6, 9, 7],
       [9, 3, 3, 9, 7, 3],
       [9, 7, 1, 9, 8, 5],
       [4, 5, 4, 5, 4, 1],
       [7, 3, 7, 4, 7, 2]])

In [133]:
arr1 = np.random.randint(1,10, size=(5,6)) #optional to mention size


In [134]:
arr1

array([[7, 6, 2, 5, 9, 8],
       [6, 7, 7, 5, 9, 5],
       [4, 7, 8, 2, 3, 4],
       [8, 1, 5, 8, 4, 8],
       [9, 4, 1, 6, 6, 1]])

In [136]:
arr1 >3 #print true if true else false

array([[ True,  True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True],
       [ True,  True,  True, False, False,  True],
       [ True, False,  True,  True,  True,  True],
       [ True,  True, False,  True,  True, False]])

In [137]:
arr1<3

array([[False, False,  True, False, False, False],
       [False, False, False, False, False, False],
       [False, False, False,  True, False, False],
       [False,  True, False, False, False, False],
       [False, False,  True, False, False,  True]])

In [138]:
arr1[0]

array([7, 6, 2, 5, 9, 8])

In [140]:
arr[0][1]

2

In [141]:
arr[0:3]

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [142]:
arr[:3]

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [144]:
arr[1:]

array([[2, 2, 2, 2],
       [2, 2, 2, 2]])

In [145]:
arr1[0:3,[0,2]]

array([[7, 2],
       [6, 7],
       [4, 8]])

In [ ]:
#slicing on both row and column
arr[0:3, 1:3] #0-2 rows and 1-2 columns

array([[2, 2],
       [2, 2],
       [2, 2]])

In [148]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))


In [153]:
arr1

array([[1, 1, 1],
       [1, 2, 2],
       [1, 2, 2]])

In [154]:
arr2

array([[1, 1, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [155]:
arr1 + arr2

array([[2, 2, 3],
       [3, 4, 3],
       [2, 3, 4]])

In [156]:
arr1 + arr #shape must be same

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

In [157]:
arr1 * arr2

array([[1, 1, 2],
       [2, 4, 2],
       [1, 2, 4]])

In [ ]:
arr1 - arr2 #index wise element substraction

array([[ 0,  0, -1],
       [-1,  0,  1],
       [ 0,  1,  0]])

In [159]:
arr1

array([[1, 1, 1],
       [1, 2, 2],
       [1, 2, 2]])

In [160]:
arr2

array([[1, 1, 2],
       [2, 2, 1],
       [1, 1, 2]])

In [162]:
arr1* arr2 #index wise multiplication

array([[1, 1, 2],
       [2, 4, 2],
       [1, 2, 4]])

In [164]:
arr1 / arr2 #index wise devision

array([[1. , 1. , 0.5],
       [0.5, 1. , 2. ],
       [1. , 2. , 1. ]])

In [167]:
#matrix multiplication different from insex wise multiplication
arr1@arr2 #we use @ for it. 1st way

array([[4, 4, 5],
       [7, 7, 8],
       [7, 7, 8]])

In [ ]:
np.dot(arr1,arr2) #2nd way to do that
#for matrix multiplication if one array is m*n dimention and array 2 is 
# p*q dimention and n = p then only we can able to do matrix multiplication 
#result shoudl me m*q

array([[4, 4, 5],
       [7, 7, 8],
       [7, 7, 8]])

In [170]:
arr3 = np.random.randint(1,10 ,(1,4))
arr4 = np.random.randint(20 ,30, (4,8))

In [171]:
arr3

array([[4, 4, 9, 7]])

In [172]:
arr4

array([[22, 24, 20, 21, 20, 28, 28, 21],
       [24, 24, 26, 28, 25, 25, 20, 23],
       [29, 20, 28, 29, 23, 20, 28, 23],
       [28, 21, 24, 20, 26, 25, 21, 26]])

In [173]:
arr3 @arr4

array([[641, 519, 604, 597, 569, 567, 591, 565]])

In [174]:
arr3/0 #does not give error give inf , inf

C:\Users\nachi\AppData\Local\Temp\ipykernel_15996\4211589366.py:1: RuntimeWarning: divide by zero encountered in divide
  arr3/0 #does not give error give inf , inf


array([[inf, inf, inf, inf]])

In [175]:
#broadcasting 
arr = np.zeros((3,4))


In [ ]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [178]:
#to add all the elements 
arr+5 
#how it adding internally.
#when we add + any number the array of that number is created.
#like we have (3,4) arrays, and adding 5 to it, it will create (3,4) array of 5 element and add to each

array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])

In [179]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [180]:
a = np.array([1,2,3,4])

In [181]:
a.ndim

1

In [183]:
a+1 # here 1 din array of 4 colum is created

array([2, 3, 4, 5])

In [189]:
s= arr + a 
#here id array will create 3 times and add those it self

In [190]:
#transpose
a.T

array([1, 2, 3, 4])

In [191]:
arr.T #3 rows 4 columsn becomes 4 rows and 3 columns

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [193]:
s

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [192]:
s.T

array([[1., 1., 1.],
       [2., 2., 2.],
       [3., 3., 3.],
       [4., 4., 4.]])

In [196]:
np.sqrt(s)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.        , 1.41421356, 1.73205081, 2.        ],
       [1.        , 1.41421356, 1.73205081, 2.        ]])

In [195]:
np.exp(s)

array([[ 2.71828183,  7.3890561 , 20.08553692, 54.59815003],
       [ 2.71828183,  7.3890561 , 20.08553692, 54.59815003],
       [ 2.71828183,  7.3890561 , 20.08553692, 54.59815003]])

In [197]:
np.log10(s)

array([[0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.        , 0.30103   , 0.47712125, 0.60205999],
       [0.        , 0.30103   , 0.47712125, 0.60205999]])

In [198]:
np.max(s)

4.0

In [199]:
np.min(s)

1.0

In [200]:
np.sum(s)

30.0