In [1]:
import numpy as np

In [3]:
arr1 = np.random.randint(1,3,(3,3))
arr2 = np.random.randint(1,3,(3,3))


In [4]:
arr1

array([[2, 2, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [5]:
arr2

array([[2, 2, 1],
       [1, 1, 1],
       [2, 2, 1]])

In [6]:
#flatten array in one dimention, any higher dimentional array will reduced into 1d
arr1.flatten()

array([2, 2, 2, 2, 2, 1, 1, 1, 1])

In [9]:
#expending dimention
#there is a method to exepend the dimention called expand expend_dim(array, axis=0/1) #0 means row and 1 means column

arr = np.array([1,2,3,4])
arr.ndim

1

In [16]:
np.expand_dims(arr,axis=0) #expand array by rows



array([[1, 2, 3, 4]])

In [18]:
np.expand_dims(arr,axis=1) #expand array by colms
#it will not add element or remove but split the elements or add the subsripts

array([[1],
       [2],
       [3],
       [4]])

In [19]:
arr.ndim

1

In [20]:
#expand dimention always increases the dimention by 1, at provided axis.
arr = np.zeros((3,4))

In [21]:
arr.ndim

2

In [24]:
np.expand_dims(arr,axis=0).ndim

3

In [26]:
a = np.array([[1],[2],[3]])

In [28]:
np.squeeze(a) #descrese dimention by one

array([1, 2, 3])

In [30]:
#to repeat the data
np.repeat(a,4) #repeat data (array, no.of repeatation)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3])

In [32]:
np.repeat(arr2,2)

array([2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1])

In [34]:
#repeat by rows wise
np.repeat(arr1, 2, axis=0) #1 means colm

array([[2, 2, 2],
       [2, 2, 2],
       [2, 2, 1],
       [2, 2, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [36]:
np.repeat(arr1,3, axis=1)

array([[2, 2, 2, 2, 2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2, 2, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [37]:
#rotate the matrix
arr = np.array([[1],[2],[3]])
arr

array([[1],
       [2],
       [3]])

In [39]:
np.roll(a,-1)

array([[2],
       [3],
       [1]])

In [ ]:
np.roll(a,-2) #roll -2 means 2 stpes 

array([[3],
       [1],
       [2]])

In [43]:
np.roll(a,-2)

array([[3],
       [1],
       [2]])

In [47]:
c = np.array([[1,2],[3,4],[5,6],[7,8]])


In [48]:
c

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [54]:
np.roll(c,-3) #only count first 3 steps then continue it

array([[4, 5],
       [6, 7],
       [8, 1],
       [2, 3]])

In [55]:
np.roll(c,-2) #only step first time then continue

array([[3, 4],
       [5, 6],
       [7, 8],
       [1, 2]])

In [57]:
np.roll(c, -2, axis=0) #it's works on rows

array([[5, 6],
       [7, 8],
       [1, 2],
       [3, 4]])

In [58]:
arr1

array([[2, 2, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [59]:
arr2

array([[2, 2, 1],
       [1, 1, 1],
       [2, 2, 1]])

In [60]:
arr1  + arr2

array([[4, 4, 3],
       [3, 3, 2],
       [3, 3, 2]])

In [61]:
arr1 - arr2

array([[ 0,  0,  1],
       [ 1,  1,  0],
       [-1, -1,  0]])

In [62]:
arr1 @ arr2

array([[10, 10,  6],
       [ 8,  8,  5],
       [ 5,  5,  3]])

In [63]:
arr1 > arr2

array([[False, False,  True],
       [ True,  True, False],
       [False, False, False]])

In [64]:
#negation

-arr1

array([[-2, -2, -2],
       [-2, -2, -1],
       [-1, -1, -1]])

In [66]:
#array option on string
st = np.array(['abc','tHe','THE','sjso'])


In [67]:
np.char.capitalize(st)

array(['Abc', 'The', 'The', 'Sjso'], dtype='<U4')

In [68]:
np.char.upper(st)

array(['ABC', 'THE', 'THE', 'SJSO'], dtype='<U4')

In [69]:
np.char.lower(st)

array(['abc', 'the', 'the', 'sjso'], dtype='<U4')

In [70]:
np.char.split(st)

array([list(['abc']), list(['tHe']), list(['THE']), list(['sjso'])],
      dtype=object)

In [72]:
np.sin(arr1)

array([[0.90929743, 0.90929743, 0.90929743],
       [0.90929743, 0.90929743, 0.84147098],
       [0.84147098, 0.84147098, 0.84147098]])

In [73]:
np.cos(arr1)

array([[-0.41614684, -0.41614684, -0.41614684],
       [-0.41614684, -0.41614684,  0.54030231],
       [ 0.54030231,  0.54030231,  0.54030231]])

In [74]:
np.tan(arr1)

array([[-2.18503986, -2.18503986, -2.18503986],
       [-2.18503986, -2.18503986,  1.55740772],
       [ 1.55740772,  1.55740772,  1.55740772]])

In [75]:
np.log10(arr1)

array([[0.30103, 0.30103, 0.30103],
       [0.30103, 0.30103, 0.     ],
       [0.     , 0.     , 0.     ]])

In [76]:
np.power(arr1,3)

array([[8, 8, 8],
       [8, 8, 1],
       [1, 1, 1]], dtype=int32)

In [77]:
np.max(arr1)

2

In [78]:
np.std(arr1)

0.4969039949999533

In [80]:
np.var(arr1) #variance

0.2469135802469136

In [83]:
np.substract(arr1,arr2)

AttributeError: module 'numpy' has no attribute 'substract'

In [84]:
np.multiply(arr1,arr2)

array([[4, 4, 2],
       [2, 2, 1],
       [2, 2, 1]])

In [86]:
np.add(arr1,arr2)

array([[4, 4, 3],
       [3, 3, 2],
       [3, 3, 2]])

In [87]:
np.square(arr1)

array([[4, 4, 4],
       [4, 4, 1],
       [1, 1, 1]])

In [88]:
#sort search
e = np.array([5,1,3,5,0])
np.sort(e)

array([0, 1, 3, 5, 5])

In [89]:
f = np.array([5,199,200,8,4,2])
np.sort(f)

array([  2,   4,   5,   8, 199, 200])

In [93]:
#to get an index to which an element should be added which will not effect the sorting order
np.searchsorted(f,33) #answer-1 will the answer

6

In [98]:
f = np.array([5,199,200,0,4,2,0,0,0,0])

#count non zero elemtnt
np.count_nonzero(f)

5

In [99]:
f[f>0]

array([  5, 199, 200,   4,   2])

In [100]:
np.where(f>0)

(array([0, 1, 2, 4, 5], dtype=int64),)

In [103]:
np.extract(f<=0,f)

array([0, 0, 0, 0, 0])

In [105]:
#bit representation of array
f.byteswap() #gives byte number of that element

array([  83886080, -956301312, -939524096,          0,   67108864,
         33554432,          0,          0,          0,          0])

In [106]:
#matrix 2nd array
import numpy.matlib as nm

In [108]:
nm.zeros(5) #it's a 2d matrix

matrix([[0., 0., 0., 0., 0.]])

In [110]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [118]:
#linear algebra 
arr1

array([[2, 2, 2],
       [2, 2, 1],
       [1, 1, 1]])

In [119]:
arr2

array([[2, 2, 1],
       [1, 1, 1],
       [2, 2, 1]])

In [120]:
arr1 @ arr2 #matrix multiplication

array([[10, 10,  6],
       [ 8,  8,  5],
       [ 5,  5,  3]])

In [121]:
#determinant
np.linalg.det(arr1)

0.0

In [126]:
np.linalg.inv(a) #must i==j

LinAlgError: Last 2 dimensions of the array must be square

In [127]:
#to solve matrix equal, all can be solve by linear equation method
a = np.array([[7,5.3,-3],[3,-5,2],[5,3,-7]])

In [128]:
a


array([[ 7. ,  5.3, -3. ],
       [ 3. , -5. ,  2. ],
       [ 5. ,  3. , -7. ]])

In [129]:
b = np.array([16,8,0])

In [130]:
np.linalg.solve(a,b)

array([2.59630607, 0.84432718, 2.21635884])