In [1]:
''' 
Data science process
CrISPDM (cross industry standard process for data mining)
it's not mandotary process to follow but best standard industry used for any data mining/modling
steps it contains
1.business understanding 
2.data understanding
3.data preparation
4.modeling
5.evalution
6.deployement

let's understand this with ex:
**predict a price of house.**
to predict the price of house, you ask business team
what factors on which the price of house depends, it depends on
1.area of house
2. no. of rooms
we understand, the scale of data, how it effective revenue, and all other factors
(this analysis is known as business understanding)

data understing 
(to understand the data) we do some analysis called
exploratory data analysis.
we may do univariate analysis (one features at a time), or biveriate (two feature), multivariant (
    more then 2 featurea at a time),
once you understand the data, you go for data preparation
and you build ml modeling, evaluate and deploye.


why we are reading pandas/numpy and all
to understand data and data preparation, we have many function present in pandas, numpy, and to visualition
data we have matplolib, seaborn.
library (contains python modules and packages)'''


" \nData science process\nCrISPDM (cross industry standard process for data mining)\nit's not mandotary process to follow but best standard industry used for any data mining/modling\nsteps it contains\n1.business understanding \n2.data understanding\n3.data preparation\n4.modeling\n5.evalution\n6.deployement\n\nlet's understand this with ex:\n**predict a price of house.**\nto predict the price of house, you ask business team\nwhat factors on which the price of house depends, it depends on\n1.area of house\n2. no. of rooms\nwe understand, the scale of data, how it effective revenue, and all other factors\n(this analysis is known as business understanding)\n\ndata understing \n(to understand the data) we do some analysis called\nexploratory data analysis.\nwe may do univariate analysis (one features at a time), or biveriate (two feature), multivariant (\n    more then 2 featurea at a time),\nonce you understand the data, you go for data preparation\nand you build ml modeling, evaluate an

In [ ]:
#faster programming language is c++,
#numpy >> numerical py. 
'''
numPy is the fundamental package for scientific computing in Python. 
It is a Python library that provides a multidimensional array object, 
various derived objects (such as masked arrays and matrices), and an assortment of 
routines for fast operations on arrays, including mathematical, logical, shape manipulation, 
sorting, selecting, I/O, discrete Fourier transforms, basic linear algebra, basic statistical
operations, random simulation and much more

numpy is developed in 2005 by travis oliphant'''

In [1]:
import numpy as np 

In [3]:
np.__version__ #show the version

'1.26.4'

In [4]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

In [5]:
lis = [1,2,3,'nachiket',True] #it's storing homogenous element





In [6]:
#but numpy stores data in array
#array is container which stores homogeous element in contigous manner


In [8]:
#why numpy :
''' 
1. computation is fast (because it store data in array, and memory is contigous)
2. it provides methematical functions for computation'''

' \n1. computation is fast (because it store data in array, and memory is contigous)\n2. it provides methematical functions for computation'

In [9]:
l = [1,2,3,4,5]
arr = np.array(l)

In [11]:
type(arr)

numpy.ndarray

In [16]:
l = [1,2,4,5.9]
print(np.array(l)) #it will store all in float

[1.  2.  4.  5.9]


In [ ]:
l1= [1,2,3,4,'nachiket']
arr= np.array(l1)


array(['1', '2', '3', '4', 'nachiket'], dtype='<U11')

In [18]:
#to see the dimention
arr.ndim

1

In [21]:
arr1 = np.array([[1,2,3,4],[5,6,7,8]])
arr1.ndim

2

In [20]:
arr1

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
#matrix : it's way to represent data in vector form
mat = np.matrix([1,2,3,4])
#matrix is specilized array it always in two dimentional (can;t 3d)

In [6]:
mat.ndim

2

In [7]:
mat

matrix([[1, 2, 3, 4]])

In [8]:
#to convert as array (more way without using np.array)
l = [1,2,3]
np.asarray(l)

array([1, 2, 3])

In [ ]:
#something is already in array is converted 
np.asarray(mat)  #mat is also an array (sub class it also convert that)

array([[1, 2, 3, 4]])

In [11]:
np.asanyarray(mat) #it will not convert sub class of array but convert other to array

matrix([[1, 2, 3, 4]])

In [12]:
np.asanyarray([1,2,3,4])

array([1, 2, 3, 4])

In [14]:
t  = ([1,2,3],[4,5,6]) #tuple to array
t
type(t)

tuple

In [15]:
np.array(t)

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
l = [1,2,3,4,5]
arr= np.array(l)

In [19]:
#accessing element of array
arr[0]

1

In [23]:
arr[0] = 500

In [24]:
arr[0] #array is mutable


500

In [26]:
#deep copy and shallow copy
a = arr

In [27]:
a


array([500,   2,   3,   4,   5])

In [28]:
arr[0] = 1000 #changing in array not in a

In [30]:
a #change in array also let change in a, this is called shallow copy

array([1000,    2,    3,    4,    5])

In [36]:
''' 
understand it, let's we have a data . elements [1,2,3,4,5], when we are doing
a=arr (means we are refering memory block of arr to a, so whenever we change the arr, a also change
it's call shallow copy)'''
b = arr.copy() #it will take some other reference and change in array will not effect any
#call deep copy


In [37]:
b

array([300,   2,   3,   4,   5])

In [38]:
arr

array([300,   2,   3,   4,   5])

In [39]:
arr[0] = 300

In [40]:
b

array([300,   2,   3,   4,   5])

In [41]:
a[2] = 300

In [42]:
arr

array([300,   2, 300,   4,   5])

In [ ]:
#to create an array
''' 
np.array (convert to array)
np.asarray (convert to array if sub class also)
np.asanyarray(doesnot convert sub classes)'''

In [45]:
#multiple ways to generate array
arr1= np.fromfunction(lambda i,j : i ==j, (3,3))
#whereever i==j, gives true and when i!=j gives false, (it's diagonal matrix)

In [46]:
arr1.ndim

2

In [49]:
arr1.shape #shape of array (elements in row and columns)

(3, 3)

In [51]:
arr1.size #gives total number of elements


9

In [56]:
arr2 = np.fromfunction(lambda i,j : i*j, (3,3))

In [57]:
arr2

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [58]:
#iterables
for i in range(5):
    print(i)

0
1
2
3
4


In [ ]:
ls = [i for i in range(5)]

[0, 1, 2, 3, 4]

In [71]:
tu = (i for i in range(5))

In [68]:
tu

<generator object <genexpr> at 0x0000021131EE16C0>

In [69]:
list(tu)

[0, 1, 2, 3, 4]

In [73]:
#how to convert that into array
np.fromiter(tu, int) #it takes iterator and takes datatype of it

array([], dtype=int32)

In [78]:
#array created using string
np.fromstring('22 23 25',sep=" ") #it should integer only (values should be numerical)

array([22., 23., 25.])

In [ ]:
#for sting character you have to use split
string = 'nachiket xyz he'
string1 = string.split(' ')
np.array(string)

array('nachiket xyz he', dtype='<U15')

In [81]:
list(range(10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [83]:
#similar function present in numpy
np.arange(1,10,0.1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9, 5. , 5.1, 5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1,
       6.2, 6.3, 6.4, 6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4,
       7.5, 7.6, 7.7, 7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7,
       8.8, 8.9, 9. , 9.1, 9.2, 9.3, 9.4, 9.5, 9.6, 9.7, 9.8, 9.9])

In [84]:
np.linspace(1,5,10) #generate 10 number between 1 to 5, 

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
np.logspace(1,5,10) #number given by log space (base is 10)

In [85]:
np.logspace(1,5,10,base=20)

array([2.00000000e+01, 7.57295802e+01, 2.86748466e+02, 1.08576705e+03,
       4.11123413e+03, 1.55671017e+04, 5.89445040e+04, 2.23192127e+05,
       8.45112304e+05, 3.20000000e+06])