In [1]:
import numpy as np

a = np.array([1, 2, 3, 4])

print(a)
print(type(a))
print(a.shape)
print(a.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)
int32


In [3]:
l=[]
for i in range(0,11):
    l.append(i)
print(l)
arr = np.array(l)
arr

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
#Create an array of all zeros (size 5)
arr2 = np.zeros(5)
arr2

array([0., 0., 0., 0., 0.])

In [11]:
#Create an array from 0 to 20 with step 2
l= []
for i in range(0,21,2):
    l.append(i)
arr3= np.array(l)
arr3.shape
arr3.dtype

dtype('int32')

In [13]:
arr5 = np.array([[1,2,3],[2,3,4]])
arr5

array([[1, 2, 3],
       [2, 3, 4]])

In [15]:
arr5.shape

(2, 3)

In [17]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr3 = np.random.rand(30)
arr3

array([0.10861532, 0.05486924, 0.17248011, 0.81832207, 0.84375275,
       0.81092744, 0.75620373, 0.82095655, 0.5287058 , 0.73644456,
       0.84436208, 0.00163969, 0.10948585, 0.4110931 , 0.77222281,
       0.92345851, 0.35285159, 0.64873419, 0.68712912, 0.77703112,
       0.44505243, 0.4690093 , 0.31122526, 0.3672831 , 0.92448645,
       0.4299921 , 0.86537081, 0.14792226, 0.81350655, 0.64928426])

In [1]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))
print(arr+5)

[10 20 30 40 50]
<class 'numpy.ndarray'>
[15 25 35 45 55]


In [2]:
import numpy as np

task1 = np.zeros(6)
print(task1)
task2 = np.ones(3)
print(task2)
task3 = np.arange(5,20,5)
print(task3)
task4 = np.linspace(1.1,1.9,4)
print(task4)

[0. 0. 0. 0. 0. 0.]
[1. 1. 1.]
[ 5 10 15]
[1.1        1.36666667 1.63333333 1.9       ]


In [3]:
task1 = np.ones((2,2))
print(task1)
task2 = np.zeros((3,4))
print(task2)
task3 = np.array([[1,2,3],[4,5,6]])
print(task3.shape)

[[1. 1.]
 [1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
(2, 3)


In [4]:
task1 = np.array([1,2,3])
print(task1.dtype)
task2= np.array([1,2,3],dtype=float)
print(task2.dtype)
task3  = np.array([1,2,3.5])
print(task3.dtype)

int32
float64
float64


In [5]:
np.array([1, True, 3])

array([1, 1, 3])

In [7]:
import numpy as np

arr = np.array([10,20,30,40,50])
print(arr[2])
print(arr[1:4])
print(arr[-1:-4:-1])
print(arr[0::2])

30
[20 30 40]
[50 40 30]
[10 30 50]


In [8]:
arr[4:1]

array([], dtype=int32)