In [2]:

import numpy as np



In [ ]:
''' 
numpy Arrays
numpy arrays are the main way we will use numpy, numpy arrays essectially come in two flavors:
vectors and matrices, vectrors are strictly 1-d arrays and matrices are 2-d (but you should note a matrics can still have only
one row or one column)'''
#creating numpy arrays
#from a python list
lst = [1,2,3,4,5]
print(lst, type(lst))
arr = np.array(lst)
print(arr, type(arr))
#arrays are homogeous in natures 
#list can store any values -
arr.dtype

[1, 2, 3, 4, 5] <class 'list'>
[1 2 3 4 5] <class 'numpy.ndarray'>


dtype('int32')

In [ ]:
arr = np.array(['1',2,3,4,5,6])
arr.dtype
#it convert all values to string because it's homogenous in nature it can store only one type of data not other


dtype('<U11')

In [9]:
arr = np.array(['hello',1,3,4,5])
print(arr,arr.dtype,type(arr))

['hello' '1' '3' '4' '5'] <U11 <class 'numpy.ndarray'>


In [ ]:
#2d array
a = [[1,2,3],[4,5,6],[7,8,9]]
print(a)
arr = np.array(a)
print(arr) #it will take 2dimentional space (which contains row and columns)

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [13]:
#built in method 
'''there are lots of built in methods to create an array lets create some'''
np.zeros([10])

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
print(np.zeros([10,10]))
print(np.zeros([10,10]).ndim)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
2


In [18]:
print(np.ones([1,4]))
print(np.ones([5,8]))

[[1. 1. 1. 1.]]
[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
#full function used to fill with a give values
#np.full([row,column], value)
np.full([5,5],7)


array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [20]:
np.full([2,3],9)

array([[9, 9, 9],
       [9, 9, 9]])

In [ ]:
#arrange funtion (it's similar to range in python)
#np.arange(start_point, end_point, step) #start point included , end point excluded, skip
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
np.arange(1,11,2) 

array([1, 3, 5, 7, 9])

In [24]:
#linsapce = linear space array
np.linspace(1,10, 5)
#provide element, between starting and ending point with proper space(linear) between them (proper distribution)
#np.linspace(start_point, end_point, how_many_values_required) (end also included)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [25]:
np.linspace(1,10,10)

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [ ]:
np.eye(5) #gives a diagonal matrix or identity matrics of 5 row and columns
#all elements are zero except diagonal

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
np.random.rand(5,3) #generate random numbers 
#we get all values between 0 and 1 not more then that in rand function 
#np.random.rand(rows,columns)

array([[0.357499  , 0.83962583, 0.62116982],
       [0.00717888, 0.52032424, 0.40966992],
       [0.89365981, 0.44614844, 0.8014018 ],
       [0.4742831 , 0.96599781, 0.44475501],
       [0.98231497, 0.18584191, 0.63334732]])

In [ ]:
np.random.randint(1,10,(3,3))
#np.random.randint(start,end, (rows,columns))
#generate random number between given values

array([[3, 2, 3],
       [1, 3, 1],
       [5, 5, 6]])

In [ ]:
arr = np.random.randn(2,4)
arr
#when we are using randn we get values between -3 to +3


array([[-0.98164715,  0.04216501, -1.95507396, -0.66543479],
       [-1.34580734,  0.7515806 ,  0.118832  , -0.4871396 ]])

In [32]:
#attributes of an array
'''introduce attributes that describe the array
'''
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
print(arr.shape) # gives number of rows and columns present in dataset (row,column)

(2, 3)


In [ ]:
print(arr.ndim) #gives dimention of given dataset

2


In [37]:
arr.size #gives number of element present in dataset

6

In [38]:
arr.dtype #gives data type of given dataset

dtype('int32')

In [39]:
#indexing and slicing
#1-d array
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[0:3])
print(arr[:4])
print(arr[-1])
print(arr[-1:])

1
[1 2 3]
[1 2 3 4]
5
[5]


In [43]:
#two-d array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr
print(arr[0]) #print(arr[row,column])
print(arr[1])
print(arr[2])
print(arr[0][2]) #or
print(arr[0,2])
print(arr[2,0])

[1 2 3]
[4 5 6]
[7 8 9]
3
3
7


In [48]:
#slicing
print(arr[0:2,0:2]) 
#print(arr[start_row:to_row, start_col :to_col]) #start includded and end excluded
print(arr[1:,1:3])


[[1 2]
 [4 5]]
[[5 6]
 [8 9]]


In [ ]:
#boolean indexing
arr = np.array([5,10,20,30,40])
print(arr>12) #gives true and false values 
print(arr[arr>12]) #to get values (it takes only true values)

[False False  True  True  True]
[20 30 40]


In [54]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr>5)
#when we are applying boolean indexing for 2-d array it will convert to one dimenetional
print(arr[arr<5])

[[False False False]
 [False False  True]
 [ True  True  True]]
[1 2 3 4]


In [58]:
#reshaping the array
arr = np.arange(1,31)
print(arr)
arr.reshape(5,6)
#only n*m = value, can be reshaped
arr.reshape(6,6) #invalid

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30]


ValueError: cannot reshape array of size 30 into shape (6,6)

In [8]:
#numpy array operations
a = [10,20,30,40]
b = [1,2,3,4]
print(a+b) #the python list will concate 
print(a*2)

[10, 20, 30, 40, 1, 2, 3, 4]
[10, 20, 30, 40, 10, 20, 30, 40]


In [9]:
#in numpy
import numpy as np
a = np.array([10,20,30,40])
b = np.array([1,2,3,4])
print(a+b)
#operations on array happens element-wise or may called indexed wise.

[11 22 33 44]


In [13]:
#the shape must be same to perform the operations
print(a-b)
print(a*b)
print(a/b) #we get a float number
print(a//b)
print(a%b)
print(a*2) #it will multiply all the numbers in array
print(b*12)


[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[10 10 10 10]
[0 0 0 0]
[20 40 60 80]
[12 24 36 48]


In [14]:
#even these things work with different shaped array the caculations will happen on every row, but dimensions must match
arr = np.array([[1,2,3],[4,5,6]])
print(arr*5)

[[ 5 10 15]
 [20 25 30]]


In [18]:
#aggregate funtions
#these function are used to calculate the statistics on arrays
arr = np.array([4,8,15,16,23,42])

print(np.sum(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.max(arr))
print(np.min(arr))
print(np.var(arr))
print(np.std(arr))

108
18.0
15.5
42
4
151.66666666666666
12.315302134607444


In [19]:
#you can also do the axis based operations row-wise and column-wise
data = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])


In [22]:
print(np.sum(data, axis=1)) #axis =1 will gives rows
print(np.sum(data, axis=0)) #axis =0 will for column
print(np.mean(data, axis=1))
print(np.mean(data,axis=0))

[ 6 15 24]
[12 15 18]
[2. 5. 8.]
[4. 5. 6.]


In [25]:
#fency indexing 
#you can pick elements from specific positions using a list/array of indices
arr = np.array([10,20,30,40,50,60])
a = [1,2,3,4,5,6]
print(a[0])
print(a[0,2]) #we cant do this 


1


TypeError: list indices must be integers or slices, not tuple

In [26]:
arr[0,2] #this will also gives an error because we need to give two square brackets


IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [28]:
print(arr[[0,2,4]])
print(arr[[1,2]])
print(arr[[3,4]])
#we can select as much as we want

[10 30 50]
[20 30]
[40 50]


In [35]:
#we can also do this in matrix
matrix = np.arange(1,13).reshape(3,4)
print(matrix)
print(matrix[[1,2,2,0],[2,3,0,0]])
#matrix[[rows],[columns]] required


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[ 7 12  9  1]


In [40]:
#conditional selections
#find values based on conditions or replace them
arr = np.array([5,12,18,7,20])
print(arr>10) #gives boolean
print(arr[arr>10]) #gives values
print(np.where(arr>10)) #gives indexes 
print(np.where(arr>10,arr,0)) #which values are more then 10 will give and remaining will fill with 0 (or which we want we can pass)

[False  True  True False  True]
[12 18 20]
(array([1, 2, 4], dtype=int64),)
[ 0 12 18  0 20]


In [42]:
#sort and ordering
# np.sort() -- returns sorted array
# np.argsort() -- return indices of sorted order
arr = np.array([23,4,1,6,3,55])
print(np.sort(arr))
print(np.argsort(arr))

[ 1  3  4  6 23 55]
[2 4 1 3 0 5]


In [48]:
#concatenation and stacking
a = np.array([1,2,3,4])
b = np.array([4,5,6,7])
print(np.concatenate((a,b)))


[1 2 3 4 4 5 6 7]


In [53]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a)
print(b)
print(np.vstack((a,b))) #a above b Vertical stack
print(np.vstack((b,a))) #b above a
print(np.hstack((a,b))) #a before b
print(np.hstack((b,a))) #b before a horizantal stack

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[5 6]
 [7 8]
 [1 2]
 [3 4]]
[[1 2 5 6]
 [3 4 7 8]]
[[5 6 1 2]
 [7 8 3 4]]


AttributeError: module 'numpy' has no attribute 'concat'